#
# MANIFEST DEFINITION FOR THE ACCOUNT SERVICE
#
# This file was initailly created from the command:
# oc expose deploy accounts \
#   --type=ClusterIP \
#   --port=8080 \
#   --dry-run=client -o yaml > deploy/service.yaml
#

apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: accounts
  name: accounts
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: accounts
  type: ClusterIP
status:
  loadBalancer: {}
