name: CI Build

on:
  ### EVENT #1 
  push:
    branches:
      - main
  ### EVENT #2
  pull_request:
    branches:
      - main

jobs:
  ### JOB #1
  build:
    
    ## Job Runner
    runs-on: ubuntu-latest
    container: python:3.9-slim

    ## Job Services
    services:
      # Database
      postgress:
        image: postgres:alpine
        ports:
          - 5432:5432
        env:
          POSTGRES_PASSWORD: pgs3cr3t
          POSTGRES_DB: testdb
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    
    ## Job Steps
    steps:
    
      # Step Action #1
      - name: Checkout
        uses: actions/checkout@v2
    
      # Step Action #2
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip wheel
          pip install -r requirements.txt       
    
      # Step Action #3
      - name: Lint with flake8
        run: |
          flake8 service --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 service --count --max-complexity=10 --max-line-length=127 --statistic
    
      # Step Action #4
      - name: Run unit tests with Nose
        run:
          nosetests
        env:
          DATABASE_URI: "postgresql://postgres:pgs3cr3t@postgres:5432/testdb" 
          






